# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.product_url: '%env(PRODUCT_URL)%'
    app.use_local_images: '%env(USE_LOCAL_IMAGES)%'
    app.images_dir: '%env(IMAGES_DIR)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\Command\ImportProductsCommand:
        arguments:
            - "%app.use_local_images%"
            - "%app.product_url%"

    App\Services\ImageHandler\ImageHandler:
        arguments:
            - "%kernel.project_dir%"
            - "%app.images_dir%"

    App\Factories\SymfonyStyleFactory: ~

    Symfony\Component\Console\Style\SymfonyStyle:
        factory: [ '@App\Factories\SymfonyStyleFactory', 'create' ]